version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/server/
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu
  - object: scripts/start.sh
    pattern: "**"
    owner: ubuntu
    group: ubuntu
    mode: 777

hooks:
  AfterInstall:
    - location: scripts/start.sh
      timeout: 60